// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDhkCv5tUynwqZJwvQzV1tOLGntPlU9z4',
    appId: '1:245613651137:web:99f3b48f04145810036040',
    messagingSenderId: '245613651137',
    projectId: 'laundry-4a2f2',
    authDomain: 'laundry-4a2f2.firebaseapp.com',
    storageBucket: 'laundry-4a2f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVUbZBrJYYqXtpGNAIqJjoj5-W6uC_fk0',
    appId: '1:245613651137:android:5c2cefd47f419752036040',
    messagingSenderId: '245613651137',
    projectId: 'laundry-4a2f2',
    storageBucket: 'laundry-4a2f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZbO7e56Kqz5siwLVYm8KHTryE1_w9aec',
    appId: '1:245613651137:ios:940bcce7d9518d38036040',
    messagingSenderId: '245613651137',
    projectId: 'laundry-4a2f2',
    storageBucket: 'laundry-4a2f2.appspot.com',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZbO7e56Kqz5siwLVYm8KHTryE1_w9aec',
    appId: '1:245613651137:ios:940bcce7d9518d38036040',
    messagingSenderId: '245613651137',
    projectId: 'laundry-4a2f2',
    storageBucket: 'laundry-4a2f2.appspot.com',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDhkCv5tUynwqZJwvQzV1tOLGntPlU9z4',
    appId: '1:245613651137:web:79ef802c52342315036040',
    messagingSenderId: '245613651137',
    projectId: 'laundry-4a2f2',
    authDomain: 'laundry-4a2f2.firebaseapp.com',
    storageBucket: 'laundry-4a2f2.appspot.com',
  );
}
